[build-system]
requires = ["setuptools>=42",
            "pymongo>=4.0.2",
            "croniter>=1.3.4",
            "kubernetes>=23.3.0",
            "python-dateutil>=2.8.2"]
build-backend = "setuptools.build_meta"